r"""
Valley-Hall unit cell: triangular lattice with a rotated C3 triangular rod.

Theory
------
Triangular Bravais lattice, one equilateral-triangle stiff inclusion per
primitive cell, scalar (antiplane-shear) waves.  Lattice vectors and the
reciprocal / high-symmetry points:

    a1 = a(1, 0),   a2 = a(1/2, sqrt3/2),
    b_i . a_j = 2 pi delta_ij,
    K  = (2 b1 + b2)/3,   K' = (b1 + 2 b2)/3   (inequivalent BZ corners).

An equilateral triangle has point group C3v (three mirror planes).  When the
triangle's mirrors are aligned with the lattice mirrors (rotation alpha = 0 mod
60 deg) the crystal is C3v at K, and the 2nd/3rd bands meet in a *symmetry-
protected, isolated* Dirac cone at K (and K').  Near K the two-band effective
Hamiltonian is

    H(delta k) = v_D ( delta k_x sigma_x + delta k_y sigma_y ) + m sigma_z,

where the Dirac mass m is generated by the C3-preserving but mirror-breaking
perturbation of rotating the triangle.  To leading order

    m(alpha)  ~  m0 sin(3 alpha),

so m = 0 at alpha = 0, 60 deg (Dirac closed) and is maximal near 30 deg; alpha
and -alpha are mirror images with opposite mass.  The gapped Dirac cone carries
Berry curvature Omega(dk) = -/+ v_D^2 m / (2 (v_D^2 |dk|^2 + m^2)^{3/2}) peaked
at the valley, giving the quantized valley Chern number

    C_v = (1/2) sgn(m)   at K,   and  -(1/2) sgn(m)  at K'   (total Chern 0,
                                                              time-reversal).

A domain wall between an alpha domain and its mirror partner (-alpha) therefore
carries a valley-Chern jump |Delta C_v| = 1 and, by bulk-edge correspondence,
one gap-traversing kink mode per valley, valley-momentum-locked and immune to
backscattering at gentle/120 deg bends.

This module builds the periodic cell mesh (gmsh) with a conforming triangular
inclusion; the returned dict is consumed by ``honeycomb_mesh.HoneycombBloch``.
"""
from __future__ import annotations

import numpy as np


def _periodic_cell(a1, a2, inclusion, h, verbose=False):
    """Mesh the rhombic cell spanned by a1,a2 with periodic BCs and a conforming
    inclusion.  ``inclusion(occ)`` adds OCC surface(s) and returns their tags.
    The single largest-area surface after fragmentation is the matrix; all
    smaller surfaces are inclusions (fiber).  Returns the standard mesh dict."""
    import gmsh
    gmsh.initialize()
    gmsh.option.setNumber("General.Terminal", 1 if verbose else 0)
    gmsh.model.add("cell")
    occ = gmsh.model.occ
    P = [occ.addPoint(0, 0, 0), occ.addPoint(*a1, 0),
         occ.addPoint(*(a1 + a2), 0), occ.addPoint(*a2, 0)]
    L = [occ.addLine(P[0], P[1]), occ.addLine(P[1], P[2]),
         occ.addLine(P[2], P[3]), occ.addLine(P[3], P[0])]
    cell = occ.addPlaneSurface([occ.addCurveLoop(L)])
    inc_tags = inclusion(occ)
    occ.fragment([(2, cell)], [(2, t) for t in inc_tags])
    occ.synchronize()

    # classify by area: the largest surface is matrix, the rest are inclusions
    areas = {tag: gmsh.model.occ.getMass(2, tag)
             for (_, tag) in gmsh.model.getEntities(2)}
    matrix_tag = max(areas, key=areas.get)
    fiber_surf = [t for t in areas if t != matrix_tag]
    matrix_surf = [matrix_tag]

    outer = {}
    for (_, tag) in gmsh.model.getEntities(1):
        m = np.array(gmsh.model.occ.getCenterOfMass(1, tag)[:2])
        for name, p0, d in [("bot", np.zeros(2), a1), ("top", a2, a1),
                            ("left", np.zeros(2), a2), ("right", a1, a2)]:
            t = np.dot(m - p0, d) / np.dot(d, d)
            if 0 <= t <= 1 and np.hypot(*(m - (p0 + t * d))) < 1e-6:
                outer.setdefault(name, []).append(tag)

    def tmat(v):
        T = np.eye(4); T[0, 3], T[1, 3] = v[0], v[1]; return T.flatten().tolist()
    gmsh.model.mesh.setPeriodic(1, outer["right"], outer["left"], tmat(a1))
    gmsh.model.mesh.setPeriodic(1, outer["top"], outer["bot"], tmat(a2))
    gmsh.option.setNumber("Mesh.MeshSizeMax", h)
    gmsh.option.setNumber("Mesh.MeshSizeMin", 0.6 * h)
    gmsh.model.mesh.generate(2)

    ntag, ncoord, _ = gmsh.model.mesh.getNodes()
    npx = ncoord.reshape(-1, 3)[:, :2]
    tag2i = {int(t): i for i, t in enumerate(ntag)}
    tris, zf = [], []
    for surf in fiber_surf + matrix_surf:
        en = gmsh.model.mesh.getElementsByType(2, surf)[1]
        for k in range(len(en) // 3):
            tris.append([tag2i[int(en[3*k+r])] for r in range(3)])
            zf.append(1.0 if surf in fiber_surf else 0.0)
    tris = np.array(tris, np.int64); zfib = np.array(zf)

    sa1, sa2 = {}, {}
    for tag in outer["right"]:
        _, sl, ma, _ = gmsh.model.mesh.getPeriodicNodes(1, tag)
        sa1.update({int(s): int(m) for s, m in zip(sl, ma)})
    for tag in outer["top"]:
        _, sl, ma, _ = gmsh.model.mesh.getPeriodicNodes(1, tag)
        sa2.update({int(s): int(m) for s, m in zip(sl, ma)})
    gmsh.finalize()

    Nn = npx.shape[0]
    i2t = {i: int(t) for t, i in tag2i.items()}
    master_t = np.arange(Nn); shift = np.zeros((Nn, 2))
    for i in range(Nn):
        tag = i2t[i]; sh = np.zeros(2)
        for _ in range(4):
            moved = False
            if tag in sa1:
                tag = sa1[tag]; sh = sh + a1; moved = True
            if tag in sa2:
                tag = sa2[tag]; sh = sh + a2; moved = True
            if not moved:
                break
        master_t[i] = tag2i[tag]; shift[i] = sh
    uniq = np.unique(master_t); remap = {int(m): r for r, m in enumerate(uniq)}
    master = np.array([remap[int(m)] for m in master_t])
    return dict(npx=npx, tris=tris, zfib=zfib, master=master, shift=shift,
                n_red=len(uniq), a1=a1, a2=a2)


def triangle_cell(alpha_deg, a=1.0, R=0.30, h=0.05, verbose=False):
    """Triangular lattice, one equilateral-triangle inclusion rotated by
    ``alpha_deg`` about the cell centroid.  alpha=0 aligns a triangle vertex
    with +y (a lattice mirror), giving the symmetric (Dirac) configuration."""
    a1 = a * np.array([1.0, 0.0])
    a2 = a * np.array([0.5, np.sqrt(3) / 2])
    ctr = (a1 + a2) / 2.0
    al = np.deg2rad(alpha_deg)

    def inclusion(occ):
        verts = []
        for k in range(3):
            th = al + np.pi / 2 + 2 * np.pi * k / 3
            verts.append(ctr + R * np.array([np.cos(th), np.sin(th)]))
        pts = [occ.addPoint(v[0], v[1], 0) for v in verts]
        lines = [occ.addLine(pts[k], pts[(k + 1) % 3]) for k in range(3)]
        surf = occ.addPlaneSurface([occ.addCurveLoop(lines)])
        return [surf]

    m = _periodic_cell(a1, a2, inclusion, h, verbose)
    m["alpha_deg"] = alpha_deg; m["R"] = R; m["ctr"] = ctr
    return m


if __name__ == "__main__":
    for al in [0.0, 15.0]:
        m = triangle_cell(al, h=0.06)
        print(f"alpha={al}: nodes {m['npx'].shape[0]} tris {m['tris'].shape[0]} "
              f"redDOF {m['n_red']} fiberfrac {m['zfib'].mean():.3f}")


def triangle_ribbon(Nx, alphaL_deg, alphaR_deg, a=1.0, R=0.44, h=0.06,
                    verbose=False):
    """Ribbon supercell: Nx triangular-lattice cells along a1 (finite, open),
    one cell along a2 (Bloch-periodic).  Triangles rotated alphaL for the left
    half and alphaR for the right half -> a domain wall at the centre.  Returns
    a mesh dict plus a2-only periodic data for a kappa=k.a2 sweep."""
    import gmsh
    a1 = a * np.array([1.0, 0.0]); a2 = a * np.array([0.5, np.sqrt(3) / 2])
    gmsh.initialize(); gmsh.option.setNumber("General.Terminal", 1 if verbose else 0)
    gmsh.model.add("ribbon"); occ = gmsh.model.occ
    # big parallelogram Nx*a1 x a2
    A1 = Nx * a1
    P = [occ.addPoint(0, 0, 0), occ.addPoint(*A1, 0),
         occ.addPoint(*(A1 + a2), 0), occ.addPoint(*a2, 0)]
    L = [occ.addLine(P[0], P[1]), occ.addLine(P[1], P[2]),
         occ.addLine(P[2], P[3]), occ.addLine(P[3], P[0])]
    cell = occ.addPlaneSurface([occ.addCurveLoop(L)])
    inc = []
    for i in range(Nx):
        al = np.deg2rad(alphaL_deg if i < Nx // 2 else alphaR_deg)
        ctr = i * a1 + (a1 + a2) / 2
        v = [ctr + R * np.array([np.cos(al + np.pi/2 + 2*np.pi*k/3),
                                 np.sin(al + np.pi/2 + 2*np.pi*k/3)]) for k in range(3)]
        pts = [occ.addPoint(*vk, 0) for vk in v]
        ln = [occ.addLine(pts[k], pts[(k+1) % 3]) for k in range(3)]
        inc.append(occ.addPlaneSurface([occ.addCurveLoop(ln)]))
    occ.fragment([(2, cell)], [(2, t) for t in inc]); occ.synchronize()
    areas = {tag: gmsh.model.occ.getMass(2, tag) for (_, tag) in gmsh.model.getEntities(2)}
    matrix_tag = max(areas, key=areas.get)
    fiber = [t for t in areas if t != matrix_tag]
    # a2-periodic edges: bottom (P0->P1) and top (P3->P2)
    bot, top = [], []
    for (_, tag) in gmsh.model.getEntities(1):
        mid = np.array(gmsh.model.occ.getCenterOfMass(1, tag)[:2])
        for name, p0, d in [("bot", np.zeros(2), A1), ("top", a2, A1)]:
            tt = np.dot(mid - p0, d) / np.dot(d, d)
            if 0 <= tt <= 1 and np.hypot(*(mid - (p0 + tt * d))) < 1e-6:
                (bot if name == "bot" else top).append(tag)
    T = np.eye(4); T[0, 3], T[1, 3] = a2[0], a2[1]
    gmsh.model.mesh.setPeriodic(1, top, bot, T.flatten().tolist())
    gmsh.option.setNumber("Mesh.MeshSizeMax", h); gmsh.option.setNumber("Mesh.MeshSizeMin", 0.6*h)
    gmsh.model.mesh.generate(2)
    ntag, nc, _ = gmsh.model.mesh.getNodes(); npx = nc.reshape(-1, 3)[:, :2]
    t2i = {int(t): i for i, t in enumerate(ntag)}
    tris, zf = [], []
    for surf in ([matrix_tag] + fiber):
        en = gmsh.model.mesh.getElementsByType(2, surf)[1]
        for k in range(len(en)//3):
            tris.append([t2i[int(en[3*k+r])] for r in range(3)])
            zf.append(0.0 if surf == matrix_tag else 1.0)
    tris = np.array(tris, np.int64); zfib = np.array(zf)
    sa2 = {}
    for tag in top:
        _, sl, ma, _ = gmsh.model.mesh.getPeriodicNodes(1, tag)
        sa2.update({int(s): int(m) for s, m in zip(sl, ma)})
    gmsh.finalize()
    Nn = npx.shape[0]; i2t = {i: int(t) for t, i in t2i.items()}
    master_t = np.arange(Nn); sph = np.zeros(Nn)
    for i in range(Nn):
        tag = i2t[i]
        if tag in sa2:
            master_t[i] = t2i[sa2[tag]]; sph[i] = 1.0
    uniq = np.unique(master_t); remap = {int(m): r for r, m in enumerate(uniq)}
    master = np.array([remap[int(m)] for m in master_t])
    return dict(npx=npx, tris=tris, zfib=zfib, master=master, sphase=sph,
                n_red=len(uniq), a1=a1, a2=a2, Nx=Nx, R=R)
