#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.7.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for element element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3






ufcx_finite_element element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3 =
{
  .signature = "Basix element (P, triangle, 1, gll_warped, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3

// Code for element element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5

int value_shape_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[1] = {4};
int reference_value_shape_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[1] = {4};
ufcx_finite_element* sub_elements_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[4] = {&element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &element_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3};


ufcx_finite_element element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5 =
{
  .signature = "blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (4,))",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .value_size = 4,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .reference_value_size = 4,
  .degree = 1,
  .block_size = 4,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 4,
  .sub_elements = sub_elements_element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .custom_element = NULL
};

// End of code for element element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5

// Code for element element_22da77b2a80eaf1d0d6654814d35b0d449cb80d4






ufcx_finite_element element_22da77b2a80eaf1d0d6654814d35b0d449cb80d4 =
{
  .signature = "Basix element (P, triangle, 1, equispaced, unset, False)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 0,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_22da77b2a80eaf1d0d6654814d35b0d449cb80d4

// Code for element element_8b77f3f235a8cac88c38307e375ffb38d1d7071a

int value_shape_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a[1] = {2};
int reference_value_shape_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a[1] = {2};
ufcx_finite_element* sub_elements_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a[2] = {&element_22da77b2a80eaf1d0d6654814d35b0d449cb80d4, &element_22da77b2a80eaf1d0d6654814d35b0d449cb80d4};


ufcx_finite_element element_8b77f3f235a8cac88c38307e375ffb38d1d7071a =
{
  .signature = "blocked element (Basix element (P, triangle, 1, equispaced, unset, False), (2,))",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = false,
  .lagrange_variant = 0,
  .dpc_variant = -1,
  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .custom_element = NULL
};

// End of code for element element_8b77f3f235a8cac88c38307e375ffb38d1d7071a

// Code for element element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7






ufcx_finite_element element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7 =
{
  .signature = "Basix element (P, triangle, 0, gll_warped, unset, True)",
  .cell_shape = triangle,
  .element_type = ufcx_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 1,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 0,
  .block_size = 1,
  .family = "P",
  .basix_family = 1,
  .basix_cell = 2,
  .discontinuous = true,
  .lagrange_variant = 1,
  .dpc_variant = -1,
  .num_sub_elements = 0,
  .sub_elements = NULL,
  .custom_element = NULL
};

// End of code for element element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7

// Code for dofmap dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3



int entity_dofs_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, gll_warped, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3,
  .entity_dof_offsets = entity_dof_offsets_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3,
  .entity_closure_dofs = entity_closure_dofs_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3

// Code for dofmap dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5

ufcx_dofmap* sub_dofmaps_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[4] = {&dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3, &dofmap_0769c9cd9a432f2ab66fc69eaeebde5107bd0ea3};

int entity_dofs_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5 =
{
  .signature = "FFCx dofmap for blocked element (Basix element (P, triangle, 1, gll_warped, unset, False), (4,))",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 4,
  .entity_dofs = entity_dofs_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .entity_dof_offsets = entity_dof_offsets_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .entity_closure_dofs = entity_closure_dofs_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
  .num_sub_dofmaps = 4,
  .sub_dofmaps = sub_dofmaps_dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5
};

// End of code for dofmap dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5

// Code for dofmap dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4



int entity_dofs_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 1, equispaced, unset, False)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4,
  .entity_dof_offsets = entity_dof_offsets_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4,
  .entity_closure_dofs = entity_closure_dofs_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4

// Code for dofmap dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a

ufcx_dofmap* sub_dofmaps_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a[2] = {&dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4, &dofmap_22da77b2a80eaf1d0d6654814d35b0d449cb80d4};

int entity_dofs_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a[3] = {0, 1, 2};

int entity_dof_offsets_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a[8] = {0, 1, 2, 3, 3, 3, 3, 3};

int entity_closure_dofs_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a[12] = {0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 2};

int entity_closure_dof_offsets_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a[8] = {0, 1, 2, 3, 5, 7, 9, 12};

ufcx_dofmap dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a =
{
  .signature = "FFCx dofmap for blocked element (Basix element (P, triangle, 1, equispaced, unset, False), (2,))",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .entity_dofs = entity_dofs_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .entity_dof_offsets = entity_dof_offsets_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .entity_closure_dofs = entity_closure_dofs_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a
};

// End of code for dofmap dofmap_8b77f3f235a8cac88c38307e375ffb38d1d7071a

// Code for dofmap dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7



int entity_dofs_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7[1] = {0};

int entity_dof_offsets_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7[8] = {0, 0, 0, 0, 0, 0, 0, 1};

int entity_closure_dofs_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7[1] = {0};

int entity_closure_dof_offsets_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7[8] = {0, 0, 0, 0, 0, 0, 0, 1};

ufcx_dofmap dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7 =
{
  .signature = "FFCx dofmap for Basix element (P, triangle, 0, gll_warped, unset, True)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 1,
  .block_size = 1,
  .entity_dofs = entity_dofs_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
  .entity_dof_offsets = entity_dof_offsets_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
  .entity_closure_dofs = entity_closure_dofs_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
  .entity_closure_dof_offsets = entity_closure_dof_offsets_dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7

// Code for integral integral_8a2acf82c4d7d9d8416bcaced9eb458404565057

void tabulate_tensor_integral_8a2acf82c4d7d9d8416bcaced9eb458404565057(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
// Quadrature rules
static const double weights_083[1] = {0.5};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE16_C1_D01_Q083[1][1][1][3] = {{{{-1.0, 0.0, 1.0}}}};
static const double FE21_C0_D10_Q083[1][1][1][3] = {{{{-1.0, 1.0, 0.0}}}};
// Quadrature loop independent computations for quadrature rule 083
double w2_d01_c1 = 0.0;
double J_c0 = 0.0;
double J_c3 = 0.0;
double J_c1 = 0.0;
double J_c2 = 0.0;
double w2_d10_c1 = 0.0;
double w2_d10_c0 = 0.0;
double w2_d01_c0 = 0.0;
double w1_d01_c1 = 0.0;
double w1_d10_c1 = 0.0;
double w1_d10_c0 = 0.0;
double w1_d01_c0 = 0.0;
double w2_d01_c3 = 0.0;
double w2_d10_c3 = 0.0;
double w2_d10_c2 = 0.0;
double w2_d01_c2 = 0.0;
double w1_d01_c3 = 0.0;
double w1_d10_c3 = 0.0;
double w1_d10_c2 = 0.0;
double w1_d01_c2 = 0.0;
for (int ic = 0; ic < 3; ++ic)
{
  w2_d01_c1 += w[13 + (ic * 4 + 1)] * FE16_C1_D01_Q083[0][0][0][ic];
  J_c0 += coordinate_dofs[3 * ic] * FE21_C0_D10_Q083[0][0][0][ic];
  J_c3 += coordinate_dofs[3 * ic + 1] * FE16_C1_D01_Q083[0][0][0][ic];
  J_c1 += coordinate_dofs[3 * ic] * FE16_C1_D01_Q083[0][0][0][ic];
  J_c2 += coordinate_dofs[3 * ic + 1] * FE21_C0_D10_Q083[0][0][0][ic];
  w2_d10_c1 += w[13 + (ic * 4 + 1)] * FE21_C0_D10_Q083[0][0][0][ic];
  w2_d10_c0 += w[13 + ic * 4] * FE21_C0_D10_Q083[0][0][0][ic];
  w2_d01_c0 += w[13 + ic * 4] * FE16_C1_D01_Q083[0][0][0][ic];
  w1_d01_c1 += w[1 + (ic * 4 + 1)] * FE16_C1_D01_Q083[0][0][0][ic];
  w1_d10_c1 += w[1 + (ic * 4 + 1)] * FE21_C0_D10_Q083[0][0][0][ic];
  w1_d10_c0 += w[1 + ic * 4] * FE21_C0_D10_Q083[0][0][0][ic];
  w1_d01_c0 += w[1 + ic * 4] * FE16_C1_D01_Q083[0][0][0][ic];
  w2_d01_c3 += w[13 + (ic * 4 + 3)] * FE16_C1_D01_Q083[0][0][0][ic];
  w2_d10_c3 += w[13 + (ic * 4 + 3)] * FE21_C0_D10_Q083[0][0][0][ic];
  w2_d10_c2 += w[13 + (ic * 4 + 2)] * FE21_C0_D10_Q083[0][0][0][ic];
  w2_d01_c2 += w[13 + (ic * 4 + 2)] * FE16_C1_D01_Q083[0][0][0][ic];
  w1_d01_c3 += w[1 + (ic * 4 + 3)] * FE16_C1_D01_Q083[0][0][0][ic];
  w1_d10_c3 += w[1 + (ic * 4 + 3)] * FE21_C0_D10_Q083[0][0][0][ic];
  w1_d10_c2 += w[1 + (ic * 4 + 2)] * FE21_C0_D10_Q083[0][0][0][ic];
  w1_d01_c2 += w[1 + (ic * 4 + 2)] * FE16_C1_D01_Q083[0][0][0][ic];
}
double sp_083[248];
sp_083[0] = cos(w[0]);
sp_083[1] = sp_083[0] * sp_083[0];
sp_083[2] = sin(w[0]);
sp_083[3] = sp_083[2] * sp_083[2];
sp_083[4] = 9.045302465247703 * sp_083[1] + 2.44223166561688 * sp_083[3];
sp_083[5] = -sp_083[2] * sp_083[0];
sp_083[6] = sp_083[5] + sp_083[5];
sp_083[7] = sp_083[4] * sp_083[6];
sp_083[8] = sp_083[0] * sp_083[2];
sp_083[9] = sp_083[8] + sp_083[8];
sp_083[10] = 9.045302465247703 * sp_083[6] + 2.44223166561688 * sp_083[9];
sp_083[11] = sp_083[10] * sp_083[1];
sp_083[12] = sp_083[7] + sp_083[11];
sp_083[13] = 2.44223166561688 * sp_083[1] + 131.6594025497166 * sp_083[3];
sp_083[14] = sp_083[13] * sp_083[9];
sp_083[15] = 2.44223166561688 * sp_083[6] + 131.6594025497166 * sp_083[9];
sp_083[16] = sp_083[15] * sp_083[3];
sp_083[17] = sp_083[14] + sp_083[16];
sp_083[18] = sp_083[12] + sp_083[17];
sp_083[19] = -sp_083[2] * (2 * sp_083[2]);
sp_083[20] = (2 * sp_083[0]) * sp_083[0];
sp_083[21] = sp_083[19] + sp_083[20];
sp_083[22] = (2 * sp_083[2]) * sp_083[0];
sp_083[23] = sp_083[21] * (5.0 * sp_083[22]);
sp_083[24] = (5.0 * sp_083[21]) * sp_083[22];
sp_083[25] = sp_083[23] + sp_083[24];
sp_083[26] = sp_083[18] + sp_083[25];
sp_083[27] = J_c0 * J_c3;
sp_083[28] = J_c1 * J_c2;
sp_083[29] = sp_083[27] - sp_083[28];
sp_083[30] = J_c0 / sp_083[29];
sp_083[31] = w2_d01_c1 * sp_083[30];
sp_083[32] = -J_c1 / sp_083[29];
sp_083[33] = w2_d10_c1 * sp_083[32];
sp_083[34] = sp_083[31] + sp_083[33];
sp_083[35] = sp_083[26] * sp_083[34];
sp_083[36] = sp_083[13] * sp_083[6];
sp_083[37] = sp_083[15] * sp_083[1];
sp_083[38] = sp_083[36] + sp_083[37];
sp_083[39] = sp_083[4] * sp_083[9];
sp_083[40] = sp_083[10] * sp_083[3];
sp_083[41] = sp_083[39] + sp_083[40];
sp_083[42] = sp_083[38] + sp_083[41];
sp_083[43] = -sp_083[2] * (-2 * sp_083[2]);
sp_083[44] = (-2 * sp_083[0]) * sp_083[0];
sp_083[45] = sp_083[43] + sp_083[44];
sp_083[46] = sp_083[45] * (5.0 * sp_083[22]);
sp_083[47] = (-2 * sp_083[2]) * sp_083[0];
sp_083[48] = (5.0 * sp_083[21]) * sp_083[47];
sp_083[49] = sp_083[46] + sp_083[48];
sp_083[50] = sp_083[42] + sp_083[49];
sp_083[51] = J_c3 / sp_083[29];
sp_083[52] = w2_d10_c0 * sp_083[51];
sp_083[53] = -J_c2 / sp_083[29];
sp_083[54] = w2_d01_c0 * sp_083[53];
sp_083[55] = sp_083[52] + sp_083[54];
sp_083[56] = sp_083[50] * sp_083[55];
sp_083[57] = sp_083[35] + sp_083[56];
sp_083[58] = -sp_083[2] * -sp_083[2];
sp_083[59] = -sp_083[0] * sp_083[0];
sp_083[60] = sp_083[58] + sp_083[59];
sp_083[61] = sp_083[4] * sp_083[60];
sp_083[62] = sp_083[10] * sp_083[5];
sp_083[63] = sp_083[61] + sp_083[62];
sp_083[64] = -sp_083[2] * sp_083[2];
sp_083[65] = sp_083[1] + sp_083[64];
sp_083[66] = sp_083[13] * sp_083[65];
sp_083[67] = sp_083[15] * sp_083[8];
sp_083[68] = sp_083[66] + sp_083[67];
sp_083[69] = sp_083[63] + sp_083[68];
sp_083[70] = -sp_083[3] + sp_083[1];
sp_083[71] = sp_083[70] * (5.0 * sp_083[21]);
sp_083[72] = sp_083[6] - sp_083[9];
sp_083[73] = sp_083[72] * (5.0 * sp_083[22]);
sp_083[74] = sp_083[71] + sp_083[73];
sp_083[75] = sp_083[69] + sp_083[74];
sp_083[76] = w2_d01_c0 * sp_083[30];
sp_083[77] = w2_d10_c0 * sp_083[32];
sp_083[78] = sp_083[76] + sp_083[77];
sp_083[79] = w2_d10_c1 * sp_083[51];
sp_083[80] = w2_d01_c1 * sp_083[53];
sp_083[81] = sp_083[79] + sp_083[80];
sp_083[82] = sp_083[78] + sp_083[81];
sp_083[83] = sp_083[75] * sp_083[82];
sp_083[84] = sp_083[57] + sp_083[83];
sp_083[85] = w1_d01_c1 * sp_083[30];
sp_083[86] = w1_d10_c1 * sp_083[32];
sp_083[87] = sp_083[85] + sp_083[86];
sp_083[88] = sp_083[84] * sp_083[87];
sp_083[89] = 2.44223166561688 * sp_083[1] + 9.045302465247703 * sp_083[3];
sp_083[90] = sp_083[89] * sp_083[6];
sp_083[91] = 2.44223166561688 * sp_083[6] + 9.045302465247703 * sp_083[9];
sp_083[92] = sp_083[91] * sp_083[1];
sp_083[93] = sp_083[90] + sp_083[92];
sp_083[94] = 131.6594025497166 * sp_083[1] + 2.44223166561688 * sp_083[3];
sp_083[95] = sp_083[94] * sp_083[9];
sp_083[96] = 131.6594025497166 * sp_083[6] + 2.44223166561688 * sp_083[9];
sp_083[97] = sp_083[96] * sp_083[3];
sp_083[98] = sp_083[95] + sp_083[97];
sp_083[99] = sp_083[93] + sp_083[98];
sp_083[100] = sp_083[21] * (5.0 * sp_083[47]);
sp_083[101] = (5.0 * sp_083[45]) * sp_083[22];
sp_083[102] = sp_083[100] + sp_083[101];
sp_083[103] = sp_083[99] + sp_083[102];
sp_083[104] = sp_083[103] * sp_083[34];
sp_083[105] = sp_083[94] * sp_083[6];
sp_083[106] = sp_083[96] * sp_083[1];
sp_083[107] = sp_083[105] + sp_083[106];
sp_083[108] = sp_083[89] * sp_083[9];
sp_083[109] = sp_083[91] * sp_083[3];
sp_083[110] = sp_083[108] + sp_083[109];
sp_083[111] = sp_083[107] + sp_083[110];
sp_083[112] = sp_083[45] * (5.0 * sp_083[47]);
sp_083[113] = (5.0 * sp_083[45]) * sp_083[47];
sp_083[114] = sp_083[112] + sp_083[113];
sp_083[115] = sp_083[111] + sp_083[114];
sp_083[116] = sp_083[115] * sp_083[55];
sp_083[117] = sp_083[104] + sp_083[116];
sp_083[118] = sp_083[89] * sp_083[60];
sp_083[119] = sp_083[91] * sp_083[5];
sp_083[120] = sp_083[118] + sp_083[119];
sp_083[121] = sp_083[94] * sp_083[65];
sp_083[122] = sp_083[96] * sp_083[8];
sp_083[123] = sp_083[121] + sp_083[122];
sp_083[124] = sp_083[120] + sp_083[123];
sp_083[125] = sp_083[70] * (5.0 * sp_083[45]);
sp_083[126] = sp_083[72] * (5.0 * sp_083[47]);
sp_083[127] = sp_083[125] + sp_083[126];
sp_083[128] = sp_083[124] + sp_083[127];
sp_083[129] = sp_083[128] * sp_083[82];
sp_083[130] = sp_083[117] + sp_083[129];
sp_083[131] = w1_d10_c0 * sp_083[51];
sp_083[132] = w1_d01_c0 * sp_083[53];
sp_083[133] = sp_083[131] + sp_083[132];
sp_083[134] = sp_083[130] * sp_083[133];
sp_083[135] = sp_083[88] + sp_083[134];
sp_083[136] = w1_d01_c0 * sp_083[30];
sp_083[137] = w1_d10_c0 * sp_083[32];
sp_083[138] = sp_083[136] + sp_083[137];
sp_083[139] = w1_d10_c1 * sp_083[51];
sp_083[140] = w1_d01_c1 * sp_083[53];
sp_083[141] = sp_083[139] + sp_083[140];
sp_083[142] = sp_083[138] + sp_083[141];
sp_083[143] = 9.045302465247703 * sp_083[5] + 2.44223166561688 * sp_083[8];
sp_083[144] = sp_083[143] * sp_083[6];
sp_083[145] = 9.045302465247703 * sp_083[60] + 2.44223166561688 * sp_083[65];
sp_083[146] = sp_083[145] * sp_083[1];
sp_083[147] = sp_083[144] + sp_083[146];
sp_083[148] = 2.44223166561688 * sp_083[5] + 131.6594025497166 * sp_083[8];
sp_083[149] = sp_083[148] * sp_083[9];
sp_083[150] = 2.44223166561688 * sp_083[60] + 131.6594025497166 * sp_083[65];
sp_083[151] = sp_083[150] * sp_083[3];
sp_083[152] = sp_083[149] + sp_083[151];
sp_083[153] = sp_083[147] + sp_083[152];
sp_083[154] = sp_083[21] * (5.0 * sp_083[70]);
sp_083[155] = (5.0 * sp_083[72]) * sp_083[22];
sp_083[156] = sp_083[154] + sp_083[155];
sp_083[157] = sp_083[153] + sp_083[156];
sp_083[158] = sp_083[157] * sp_083[34];
sp_083[159] = sp_083[148] * sp_083[6];
sp_083[160] = sp_083[150] * sp_083[1];
sp_083[161] = sp_083[159] + sp_083[160];
sp_083[162] = sp_083[143] * sp_083[9];
sp_083[163] = sp_083[145] * sp_083[3];
sp_083[164] = sp_083[162] + sp_083[163];
sp_083[165] = sp_083[161] + sp_083[164];
sp_083[166] = sp_083[45] * (5.0 * sp_083[70]);
sp_083[167] = (5.0 * sp_083[72]) * sp_083[47];
sp_083[168] = sp_083[166] + sp_083[167];
sp_083[169] = sp_083[165] + sp_083[168];
sp_083[170] = sp_083[169] * sp_083[55];
sp_083[171] = sp_083[158] + sp_083[170];
sp_083[172] = sp_083[143] * sp_083[60];
sp_083[173] = sp_083[145] * sp_083[5];
sp_083[174] = sp_083[172] + sp_083[173];
sp_083[175] = sp_083[148] * sp_083[65];
sp_083[176] = sp_083[150] * sp_083[8];
sp_083[177] = sp_083[175] + sp_083[176];
sp_083[178] = sp_083[174] + sp_083[177];
sp_083[179] = sp_083[70] * (5.0 * sp_083[72]);
sp_083[180] = sp_083[72] * (5.0 * sp_083[70]);
sp_083[181] = sp_083[179] + sp_083[180];
sp_083[182] = sp_083[178] + sp_083[181];
sp_083[183] = sp_083[182] * sp_083[82];
sp_083[184] = sp_083[171] + sp_083[183];
sp_083[185] = sp_083[142] * sp_083[184];
sp_083[186] = sp_083[135] + sp_083[185];
sp_083[187] = w2_d01_c3 * sp_083[30];
sp_083[188] = w2_d10_c3 * sp_083[32];
sp_083[189] = sp_083[187] + sp_083[188];
sp_083[190] = sp_083[26] * sp_083[189];
sp_083[191] = w2_d10_c2 * sp_083[51];
sp_083[192] = w2_d01_c2 * sp_083[53];
sp_083[193] = sp_083[191] + sp_083[192];
sp_083[194] = sp_083[50] * sp_083[193];
sp_083[195] = sp_083[190] + sp_083[194];
sp_083[196] = w2_d01_c2 * sp_083[30];
sp_083[197] = w2_d10_c2 * sp_083[32];
sp_083[198] = sp_083[196] + sp_083[197];
sp_083[199] = w2_d10_c3 * sp_083[51];
sp_083[200] = w2_d01_c3 * sp_083[53];
sp_083[201] = sp_083[199] + sp_083[200];
sp_083[202] = sp_083[198] + sp_083[201];
sp_083[203] = sp_083[75] * sp_083[202];
sp_083[204] = sp_083[195] + sp_083[203];
sp_083[205] = sp_083[204] * sp_083[87];
sp_083[206] = sp_083[103] * sp_083[189];
sp_083[207] = sp_083[115] * sp_083[193];
sp_083[208] = sp_083[206] + sp_083[207];
sp_083[209] = sp_083[128] * sp_083[202];
sp_083[210] = sp_083[208] + sp_083[209];
sp_083[211] = sp_083[210] * sp_083[133];
sp_083[212] = sp_083[205] + sp_083[211];
sp_083[213] = sp_083[157] * sp_083[189];
sp_083[214] = sp_083[169] * sp_083[193];
sp_083[215] = sp_083[213] + sp_083[214];
sp_083[216] = sp_083[182] * sp_083[202];
sp_083[217] = sp_083[215] + sp_083[216];
sp_083[218] = sp_083[142] * sp_083[217];
sp_083[219] = sp_083[212] + sp_083[218];
sp_083[220] = w1_d01_c3 * sp_083[30];
sp_083[221] = w1_d10_c3 * sp_083[32];
sp_083[222] = sp_083[220] + sp_083[221];
sp_083[223] = sp_083[84] * sp_083[222];
sp_083[224] = w1_d10_c2 * sp_083[51];
sp_083[225] = w1_d01_c2 * sp_083[53];
sp_083[226] = sp_083[224] + sp_083[225];
sp_083[227] = sp_083[130] * sp_083[226];
sp_083[228] = sp_083[223] + sp_083[227];
sp_083[229] = w1_d01_c2 * sp_083[30];
sp_083[230] = w1_d10_c2 * sp_083[32];
sp_083[231] = sp_083[229] + sp_083[230];
sp_083[232] = w1_d10_c3 * sp_083[51];
sp_083[233] = w1_d01_c3 * sp_083[53];
sp_083[234] = sp_083[232] + sp_083[233];
sp_083[235] = sp_083[231] + sp_083[234];
sp_083[236] = sp_083[235] * sp_083[184];
sp_083[237] = sp_083[228] + sp_083[236];
sp_083[238] = 0.04 * sp_083[219] - 0.04 * sp_083[237];
sp_083[239] = sp_083[186] + sp_083[238];
sp_083[240] = sp_083[204] * sp_083[222];
sp_083[241] = sp_083[210] * sp_083[226];
sp_083[242] = sp_083[240] + sp_083[241];
sp_083[243] = sp_083[235] * sp_083[217];
sp_083[244] = sp_083[242] + sp_083[243];
sp_083[245] = sp_083[239] + sp_083[244];
sp_083[246] = fabs(sp_083[29]);
sp_083[247] = sp_083[245] * sp_083[246];
for (int iq = 0; iq < 1; ++iq)
{
  double fw0 = sp_083[247] * weights_083[iq];
  for (int i = 0; i < 1; ++i)
  {
    A[i] += fw0 * 1;
  }
}

}

bool enabled_coefficients_integral_8a2acf82c4d7d9d8416bcaced9eb458404565057[3] = {1, 1, 1};

ufcx_integral integral_8a2acf82c4d7d9d8416bcaced9eb458404565057 =
{
  .enabled_coefficients = enabled_coefficients_integral_8a2acf82c4d7d9d8416bcaced9eb458404565057,
  .tabulate_tensor_float64 = tabulate_tensor_integral_8a2acf82c4d7d9d8416bcaced9eb458404565057,
  .needs_facet_permutations = false,
  .coordinate_element = &element_8b77f3f235a8cac88c38307e375ffb38d1d7071a,
};

// End of code for integral integral_8a2acf82c4d7d9d8416bcaced9eb458404565057

// Code for form form_53fb523088e6968cba924368821f7435311531f9

int original_coefficient_position_form_53fb523088e6968cba924368821f7435311531f9[3] = {0, 3, 4};
ufcx_dofmap* dofmaps_form_53fb523088e6968cba924368821f7435311531f9[4] = {&dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7, &dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7, &dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5, &dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5};
ufcx_finite_element* finite_elements_form_53fb523088e6968cba924368821f7435311531f9[4] = {&element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7, &element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7, &element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5, &element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5};
int form_integral_offsets_form_53fb523088e6968cba924368821f7435311531f9[4] = {0, 1, 1, 1};
static ufcx_integral* form_integrals_form_53fb523088e6968cba924368821f7435311531f9[1] = {&integral_8a2acf82c4d7d9d8416bcaced9eb458404565057};
int form_integral_ids_form_53fb523088e6968cba924368821f7435311531f9[1] = {-1};

// Return a list of the coefficient names.
const char** coefficient_name_form_53fb523088e6968cba924368821f7435311531f9(void)
{
static const char* names[3] = {"w0", "w1", "w2"};
return names;
}

// Return a list of the constant names.
const char** constant_name_form_53fb523088e6968cba924368821f7435311531f9(void)
{
return NULL;
}

ufcx_form form_53fb523088e6968cba924368821f7435311531f9 =
{

  .signature = "73cdef2dfdebb1e54b4bee5057bc54ad536733e5145e6be60d3e47b8d372685f5a43523a26bfac8e44e51702459ce3a9d25d76a45a12810bcd98ce324f25b5b6",
  .rank = 1,
  .num_coefficients = 3,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_53fb523088e6968cba924368821f7435311531f9,

  .coefficient_name_map = coefficient_name_form_53fb523088e6968cba924368821f7435311531f9,
  .constant_name_map = constant_name_form_53fb523088e6968cba924368821f7435311531f9,

  .finite_elements = finite_elements_form_53fb523088e6968cba924368821f7435311531f9,
  .dofmaps = dofmaps_form_53fb523088e6968cba924368821f7435311531f9,

  .form_integrals = form_integrals_form_53fb523088e6968cba924368821f7435311531f9,
  .form_integral_ids = form_integral_ids_form_53fb523088e6968cba924368821f7435311531f9,
  .form_integral_offsets = form_integral_offsets_form_53fb523088e6968cba924368821f7435311531f9
};

// Alias name
ufcx_form* form_libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433_0 = &form_53fb523088e6968cba924368821f7435311531f9;

ufcx_function_space* functionspace_form_libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433_0(const char* function_name)
{
static ufcx_function_space functionspace_v_0 =
{
.finite_element = &element_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
.dofmap = &dofmap_ba44e65cf5e9d26fb081d24ed9f8ea2b768553e7,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
static ufcx_function_space functionspace_f =
{
.finite_element = &element_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
.dofmap = &dofmap_044042adb23eae56d2cc20b3084a2f8d3e8ce3b5,
.geometry_family = "P",
.geometry_degree = 1,
.geometry_basix_cell = 2,
.geometry_basix_variant = 0
};
if (strcmp(function_name, "v_0") == 0) return &functionspace_v_0;
if (strcmp(function_name, "f") == 0) return &functionspace_f;
return NULL;

}

// End of code for form form_53fb523088e6968cba924368821f7435311531f9


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 52), // char const * *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *)
/*  3 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // _cffi_double_complex_t *
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // _cffi_double_complex_t const *
/*  5 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // double const *
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // int const *
/*  8 */ _CFFI_OP(_CFFI_OP_POINTER, 74), // uint8_t const *
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *)
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // _cffi_float_complex_t *
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // _cffi_float_complex_t const *
/* 13 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 14 */ _CFFI_OP(_CFFI_OP_POINTER, 56), // float const *
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // double *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 25 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 27 */ _CFFI_OP(_CFFI_OP_POINTER, 56), // float *
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 14),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 33 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(int *, int, int)
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // int *
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 38 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION, 81), // void()(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 57), // long double *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 57), // long double const *
/* 42 */ _CFFI_OP(_CFFI_OP_NOOP, 41),
/* 43 */ _CFFI_OP(_CFFI_OP_NOOP, 41),
/* 44 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 45 */ _CFFI_OP(_CFFI_OP_NOOP, 8),
/* 46 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 47 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // _Bool const *
/* 48 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 49 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // _cffi_double_complex_t
/* 50 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // _cffi_float_complex_t
/* 51 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // char const * *(*)(void)
/* 52 */ _CFFI_OP(_CFFI_OP_POINTER, 53), // char const * *
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // char const *
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 56 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 57 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 15), // long double
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 59), // ufcx_basix_custom_finite_element *
/* 59 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_basix_custom_finite_element
/* 60 */ _CFFI_OP(_CFFI_OP_POINTER, 61), // ufcx_dofmap * *
/* 61 */ _CFFI_OP(_CFFI_OP_POINTER, 62), // ufcx_dofmap *
/* 62 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_dofmap
/* 63 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_element_type
/* 64 */ _CFFI_OP(_CFFI_OP_POINTER, 65), // ufcx_finite_element * *
/* 65 */ _CFFI_OP(_CFFI_OP_POINTER, 66), // ufcx_finite_element *
/* 66 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufcx_finite_element
/* 67 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ufcx_form
/* 68 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // ufcx_function_space
/* 69 */ _CFFI_OP(_CFFI_OP_POINTER, 70), // ufcx_integral * *
/* 70 */ _CFFI_OP(_CFFI_OP_POINTER, 71), // ufcx_integral *
/* 71 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // ufcx_integral
/* 72 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ufcx_integral_type
/* 73 */ _CFFI_OP(_CFFI_OP_ENUM, 2), // ufcx_shape
/* 74 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 75 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // void(*)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *)
/* 76 */ _CFFI_OP(_CFFI_OP_POINTER, 10), // void(*)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *)
/* 77 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *)
/* 78 */ _CFFI_OP(_CFFI_OP_POINTER, 26), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *)
/* 79 */ _CFFI_OP(_CFFI_OP_POINTER, 34), // void(*)(int *, int, int)
/* 80 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // void(*)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *)
/* 81 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_ufcx_basix_element(unsigned long long *o)
{
  int n = (ufcx_basix_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_element) | 0);  /* check that ufcx_basix_element is an integer */
  return n;
}

static int _cffi_const_ufcx_mixed_element(unsigned long long *o)
{
  int n = (ufcx_mixed_element) <= 0;
  *o = (unsigned long long)((ufcx_mixed_element) | 0);  /* check that ufcx_mixed_element is an integer */
  return n;
}

static int _cffi_const_ufcx_quadrature_element(unsigned long long *o)
{
  int n = (ufcx_quadrature_element) <= 0;
  *o = (unsigned long long)((ufcx_quadrature_element) | 0);  /* check that ufcx_quadrature_element is an integer */
  return n;
}

static int _cffi_const_ufcx_basix_custom_element(unsigned long long *o)
{
  int n = (ufcx_basix_custom_element) <= 0;
  *o = (unsigned long long)((ufcx_basix_custom_element) | 0);  /* check that ufcx_basix_custom_element is an integer */
  return n;
}

static int _cffi_const_ufcx_real_element(unsigned long long *o)
{
  int n = (ufcx_real_element) <= 0;
  *o = (unsigned long long)((ufcx_real_element) | 0);  /* check that ufcx_real_element is an integer */
  return n;
}

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_prism(unsigned long long *o)
{
  int n = (prism) <= 0;
  *o = (unsigned long long)((prism) | 0);  /* check that prism is an integer */
  return n;
}

static int _cffi_const_pyramid(unsigned long long *o)
{
  int n = (pyramid) <= 0;
  *o = (unsigned long long)((pyramid) | 0);  /* check that pyramid is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_dofmap(ufcx_dofmap *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->num_global_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_global_support_dofs' is an integer */
  (void)((p->num_element_support_dofs) | 0);  /* check that 'ufcx_dofmap.num_element_support_dofs' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_dofmap.block_size' is an integer */
  { int * *tmp = &p->entity_dofs; (void)tmp; }
  { int * *tmp = &p->entity_dof_offsets; (void)tmp; }
  { int * *tmp = &p->entity_closure_dofs; (void)tmp; }
  { int * *tmp = &p->entity_closure_dof_offsets; (void)tmp; }
  { int * *tmp = &p->num_entity_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_dofs; (void)tmp; }
  { int * *tmp = &p->num_entity_closure_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_closure_dofs; (void)tmp; }
  (void)((p->num_sub_dofmaps) | 0);  /* check that 'ufcx_dofmap.num_sub_dofmaps' is an integer */
  { ufcx_dofmap * * *tmp = &p->sub_dofmaps; (void)tmp; }
}
struct _cffi_align__ufcx_dofmap { char x; ufcx_dofmap y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_finite_element(ufcx_finite_element *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufcx_shape *tmp = &p->cell_shape; (void)tmp; }
  { ufcx_element_type *tmp = &p->element_type; (void)tmp; }
  (void)((p->topological_dimension) | 0);  /* check that 'ufcx_finite_element.topological_dimension' is an integer */
  (void)((p->geometric_dimension) | 0);  /* check that 'ufcx_finite_element.geometric_dimension' is an integer */
  (void)((p->space_dimension) | 0);  /* check that 'ufcx_finite_element.space_dimension' is an integer */
  (void)((p->value_rank) | 0);  /* check that 'ufcx_finite_element.value_rank' is an integer */
  { int * *tmp = &p->value_shape; (void)tmp; }
  (void)((p->value_size) | 0);  /* check that 'ufcx_finite_element.value_size' is an integer */
  (void)((p->reference_value_rank) | 0);  /* check that 'ufcx_finite_element.reference_value_rank' is an integer */
  { int * *tmp = &p->reference_value_shape; (void)tmp; }
  (void)((p->reference_value_size) | 0);  /* check that 'ufcx_finite_element.reference_value_size' is an integer */
  (void)((p->degree) | 0);  /* check that 'ufcx_finite_element.degree' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufcx_finite_element.block_size' is an integer */
  { char const * *tmp = &p->family; (void)tmp; }
  (void)((p->basix_family) | 0);  /* check that 'ufcx_finite_element.basix_family' is an integer */
  (void)((p->basix_cell) | 0);  /* check that 'ufcx_finite_element.basix_cell' is an integer */
  (void)((p->discontinuous) | 0);  /* check that 'ufcx_finite_element.discontinuous' is an integer */
  (void)((p->lagrange_variant) | 0);  /* check that 'ufcx_finite_element.lagrange_variant' is an integer */
  (void)((p->dpc_variant) | 0);  /* check that 'ufcx_finite_element.dpc_variant' is an integer */
  (void)((p->num_sub_elements) | 0);  /* check that 'ufcx_finite_element.num_sub_elements' is an integer */
  { ufcx_finite_element * * *tmp = &p->sub_elements; (void)tmp; }
  { ufcx_basix_custom_finite_element * *tmp = &p->custom_element; (void)tmp; }
}
struct _cffi_align__ufcx_finite_element { char x; ufcx_finite_element y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_position; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->coefficient_name_map; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->constant_name_map; (void)tmp; }
  { ufcx_finite_element * * *tmp = &p->finite_elements; (void)tmp; }
  { ufcx_dofmap * * *tmp = &p->dofmaps; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(long double *, long double const *, long double const *, long double const *, int const *, uint8_t const *) = &p->tabulate_tensor_longdouble; (void)tmp; }
  { void(* *tmp)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  { ufcx_finite_element * *tmp = &p->coordinate_element; (void)tmp; }
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_53fb523088e6968cba924368821f7435311531f9(void)
{
  return &(form_53fb523088e6968cba924368821f7435311531f9);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_53fb523088e6968cba924368821f7435311531f9", (void *)_cffi_var_form_53fb523088e6968cba924368821f7435311531f9, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 67), (void *)0 },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "prism", (void *)_cffi_const_prism, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "pyramid", (void *)_cffi_const_pyramid, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_custom_element", (void *)_cffi_const_ufcx_basix_custom_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_basix_element", (void *)_cffi_const_ufcx_basix_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_mixed_element", (void *)_cffi_const_ufcx_mixed_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_quadrature_element", (void *)_cffi_const_ufcx_quadrature_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ufcx_real_element", (void *)_cffi_const_ufcx_real_element, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_dofmap, signature),
                 sizeof(((ufcx_dofmap *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "num_global_support_dofs", offsetof(ufcx_dofmap, num_global_support_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_global_support_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "num_element_support_dofs", offsetof(ufcx_dofmap, num_element_support_dofs),
                                sizeof(((ufcx_dofmap *)0)->num_element_support_dofs),
                                _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "block_size", offsetof(ufcx_dofmap, block_size),
                  sizeof(((ufcx_dofmap *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "entity_dofs", offsetof(ufcx_dofmap, entity_dofs),
                   sizeof(((ufcx_dofmap *)0)->entity_dofs),
                   _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "entity_dof_offsets", offsetof(ufcx_dofmap, entity_dof_offsets),
                          sizeof(((ufcx_dofmap *)0)->entity_dof_offsets),
                          _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "entity_closure_dofs", offsetof(ufcx_dofmap, entity_closure_dofs),
                           sizeof(((ufcx_dofmap *)0)->entity_closure_dofs),
                           _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "entity_closure_dof_offsets", offsetof(ufcx_dofmap, entity_closure_dof_offsets),
                                  sizeof(((ufcx_dofmap *)0)->entity_closure_dof_offsets),
                                  _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "num_entity_dofs", offsetof(ufcx_dofmap, num_entity_dofs),
                       sizeof(((ufcx_dofmap *)0)->num_entity_dofs),
                       _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "tabulate_entity_dofs", offsetof(ufcx_dofmap, tabulate_entity_dofs),
                            sizeof(((ufcx_dofmap *)0)->tabulate_entity_dofs),
                            _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "num_entity_closure_dofs", offsetof(ufcx_dofmap, num_entity_closure_dofs),
                               sizeof(((ufcx_dofmap *)0)->num_entity_closure_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "tabulate_entity_closure_dofs", offsetof(ufcx_dofmap, tabulate_entity_closure_dofs),
                                    sizeof(((ufcx_dofmap *)0)->tabulate_entity_closure_dofs),
                                    _CFFI_OP(_CFFI_OP_NOOP, 79) },
  { "num_sub_dofmaps", offsetof(ufcx_dofmap, num_sub_dofmaps),
                       sizeof(((ufcx_dofmap *)0)->num_sub_dofmaps),
                       _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "sub_dofmaps", offsetof(ufcx_dofmap, sub_dofmaps),
                   sizeof(((ufcx_dofmap *)0)->sub_dofmaps),
                   _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "signature", offsetof(ufcx_finite_element, signature),
                 sizeof(((ufcx_finite_element *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "cell_shape", offsetof(ufcx_finite_element, cell_shape),
                  sizeof(((ufcx_finite_element *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 73) },
  { "element_type", offsetof(ufcx_finite_element, element_type),
                    sizeof(((ufcx_finite_element *)0)->element_type),
                    _CFFI_OP(_CFFI_OP_NOOP, 63) },
  { "topological_dimension", offsetof(ufcx_finite_element, topological_dimension),
                             sizeof(((ufcx_finite_element *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "geometric_dimension", offsetof(ufcx_finite_element, geometric_dimension),
                           sizeof(((ufcx_finite_element *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "space_dimension", offsetof(ufcx_finite_element, space_dimension),
                       sizeof(((ufcx_finite_element *)0)->space_dimension),
                       _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "value_rank", offsetof(ufcx_finite_element, value_rank),
                  sizeof(((ufcx_finite_element *)0)->value_rank),
                  _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "value_shape", offsetof(ufcx_finite_element, value_shape),
                   sizeof(((ufcx_finite_element *)0)->value_shape),
                   _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "value_size", offsetof(ufcx_finite_element, value_size),
                  sizeof(((ufcx_finite_element *)0)->value_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "reference_value_rank", offsetof(ufcx_finite_element, reference_value_rank),
                            sizeof(((ufcx_finite_element *)0)->reference_value_rank),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "reference_value_shape", offsetof(ufcx_finite_element, reference_value_shape),
                             sizeof(((ufcx_finite_element *)0)->reference_value_shape),
                             _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "reference_value_size", offsetof(ufcx_finite_element, reference_value_size),
                            sizeof(((ufcx_finite_element *)0)->reference_value_size),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "degree", offsetof(ufcx_finite_element, degree),
              sizeof(((ufcx_finite_element *)0)->degree),
              _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "block_size", offsetof(ufcx_finite_element, block_size),
                  sizeof(((ufcx_finite_element *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "family", offsetof(ufcx_finite_element, family),
              sizeof(((ufcx_finite_element *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "basix_family", offsetof(ufcx_finite_element, basix_family),
                    sizeof(((ufcx_finite_element *)0)->basix_family),
                    _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "basix_cell", offsetof(ufcx_finite_element, basix_cell),
                  sizeof(((ufcx_finite_element *)0)->basix_cell),
                  _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "discontinuous", offsetof(ufcx_finite_element, discontinuous),
                     sizeof(((ufcx_finite_element *)0)->discontinuous),
                     _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "lagrange_variant", offsetof(ufcx_finite_element, lagrange_variant),
                        sizeof(((ufcx_finite_element *)0)->lagrange_variant),
                        _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "dpc_variant", offsetof(ufcx_finite_element, dpc_variant),
                   sizeof(((ufcx_finite_element *)0)->dpc_variant),
                   _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "num_sub_elements", offsetof(ufcx_finite_element, num_sub_elements),
                        sizeof(((ufcx_finite_element *)0)->num_sub_elements),
                        _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "sub_elements", offsetof(ufcx_finite_element, sub_elements),
                    sizeof(((ufcx_finite_element *)0)->sub_elements),
                    _CFFI_OP(_CFFI_OP_NOOP, 64) },
  { "custom_element", offsetof(ufcx_finite_element, custom_element),
                      sizeof(((ufcx_finite_element *)0)->custom_element),
                      _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "original_coefficient_position", offsetof(ufcx_form, original_coefficient_position),
                                     sizeof(((ufcx_form *)0)->original_coefficient_position),
                                     _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 51) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 51) },
  { "finite_elements", offsetof(ufcx_form, finite_elements),
                       sizeof(((ufcx_form *)0)->finite_elements),
                       _CFFI_OP(_CFFI_OP_NOOP, 64) },
  { "dofmaps", offsetof(ufcx_form, dofmaps),
               sizeof(((ufcx_form *)0)->dofmaps),
               _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 69) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 78) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 77) },
  { "tabulate_tensor_longdouble", offsetof(ufcx_integral, tabulate_tensor_longdouble),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_longdouble),
                                  _CFFI_OP(_CFFI_OP_NOOP, 80) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 76) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 75) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 48) },
  { "coordinate_element", offsetof(ufcx_integral, coordinate_element),
                          sizeof(((ufcx_integral *)0)->coordinate_element),
                          _CFFI_OP(_CFFI_OP_NOOP, 65) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_basix_custom_finite_element", 59, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_dofmap", 62, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_dofmap), offsetof(struct _cffi_align__ufcx_dofmap, y), 0, 14 },
  { "ufcx_finite_element", 66, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_finite_element), offsetof(struct _cffi_align__ufcx_finite_element, y), 14, 23 },
  { "ufcx_form", 67, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 37, 12 },
  { "ufcx_function_space", 68, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
  { "ufcx_integral", 71, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 49, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_element_type", 63, _cffi_prim_int(sizeof(ufcx_element_type), ((ufcx_element_type)-1) <= 0),
    "ufcx_basix_element,ufcx_mixed_element,ufcx_quadrature_element,ufcx_basix_custom_element,ufcx_real_element" },
  { "$ufcx_integral_type", 72, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
  { "$ufcx_shape", 73, _cffi_prim_int(sizeof(ufcx_shape), ((ufcx_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex,prism,pyramid" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_basix_custom_finite_element", 59 },
  { "ufcx_dofmap", 62 },
  { "ufcx_element_type", 63 },
  { "ufcx_finite_element", 66 },
  { "ufcx_form", 67 },
  { "ufcx_function_space", 68 },
  { "ufcx_integral", 71 },
  { "ufcx_integral_type", 72 },
  { "ufcx_shape", 73 },
  { "ufcx_tabulate_tensor_complex128", 2 },
  { "ufcx_tabulate_tensor_complex64", 10 },
  { "ufcx_tabulate_tensor_float32", 26 },
  { "ufcx_tabulate_tensor_float64", 18 },
  { "ufcx_tabulate_tensor_longdouble", 39 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  17,  /* num_globals */
  6,  /* num_struct_unions */
  3,  /* num_enums */
  14,  /* num_typenames */
  NULL,  /* no includes */
  82,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433(void) { return NULL; }
#  else
     initlibffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433(void)
{
  return _cffi_init("libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433(void)
{
  _cffi_init("libffcx_forms_efbe095ff7a8e274a2574174d9051ea26c449433", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
